version: '3.1'

services:
  web:
    build: ./TypeScript-Node-Starter
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: "mongodb://root:Password1!@maindb:27017/"
      MONGODB_URI_LOCAL: "mongodb://root:Password1!@maindb:27017/"
      SESSION_SECRET: sessionsecret
      FACEBOOK_ID: facebookID
      FACEBOOK_SECRET: facebooksecret
      SENDGRID_USER: myusername
      SENDGRID_PASSWORD: mysecurepassword
      PORT: 3000
      
  maindb:
    image: mongo:4.4.6
    environment:
      
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Password1!
      
    volumes:
      - maindb:/data/db
volumes:
  maindb: